### ISSUE TITLE
Release on other platform

### ISSUE THREAD

**Issue by KorewaLidesu** [fonnymunkey/spark#1]
Could there be chance for it to be host on other platform such as CurseForge and maven? (Or Github Release)
Also try make GHA script for automate build the mod

**Comment by fonnymunkey** [comment]
Added workflow for building jar.
Added Github Release [v1.11.0](https://github.com/fonnymunkey/spark/releases/tag/v1.11.0)
It is already uploaded to Curseforge, but it has been sitting waiting approval.

**Comment by fonnymunkey** [comment]
Now approved on [Curseforge](https://legacy.curseforge.com/minecraft/mc-mods/spark-unforged)
