### ISSUE TITLE
Bug with loli asm

### ISSUE THREAD

**Issue by ferreiraalex** [fonnymunkey/spark#2]
https://i.imgur.com/dlclLth.png

**Comment by dima-dencep** [comment]
https://github.com/dimadencep/LoliASM

**Comment by ferreiraalex** [comment]
what i can take jar mod?

**Comment by fonnymunkey** [comment]
That mod is limiting a maximum version of spark allowed to run, I can't do anything about that.
Make an issue on their github to remove the maximum version limit if you want to use them together.

**Comment by fonnymunkey** [comment]
FermiumASM has been created as a replacement for LoliASM/CensoredASM/NormalASM
It is compatible with Spark Unforged, Curseforge and Modrinth are pending approval as of this post.
Github Release: https://github.com/fonnymunkey/FermiumASM/releases/tag/Fermium-5.18
Curseforge: https://legacy.curseforge.com/minecraft/mc-mods/fermiumasm
Modrinth: https://modrinth.com/mod/fermiumasm
