### ISSUE TITLE
Crash during init phase: java.lang.ClassCastException: net.minecraft.client.Minecraft cannot be cast to me.lucko.spark.forge.mixin.MinecraftAccessorMixin

### ISSUE THREAD

**Issue by ProjectHSI** [fonnymunkey/spark#4]
During the initialization phase (referred to as "Initialization Phase 2" (idk if it was 2 or 3)), spark appears to cause the game to crash. The error message is in the title. Logs are attached.
[Relavent.zip](https://github.com/fonnymunkey/spark/files/13806176/Relavent.zip)

**Comment by ProjectHSI** [comment]
This is some information I've gathered about the crash report so that the mod author can more easily figure out stuff. If you're not the mod author or trying to fix this problem via a PR, you can ignore this, otherwise, continue reading.

Note: All links are permalinks, so unless GitHub makes a change to their URLs they'll always point to the issue at hand.

- Line: [73](https://github.com/fonnymunkey/spark/blob/95644e1901c13436b5372f5a9301b39856afaacf/spark-forge/src/main/java/me/lucko/spark/forge/plugin/ForgeClientSparkPlugin.java#L73)
- Package: `me.lucko.spark.forge.plugin`
- Class: `ForgeClientSparkPlugin`
- File: [spark-forge/src/main/java/me/lucko/spark/forge/plugin/ForgeClientSparkPlugin.java](https://github.com/fonnymunkey/spark/blob/95644e1901c13436b5372f5a9301b39856afaacf/spark-forge/src/main/java/me/lucko/spark/forge/plugin/ForgeClientSparkPlugin.java) ([Diff](https://github.com/fonnymunkey/spark/commit/95644e1901c13436b5372f5a9301b39856afaacf#diff-5d02a3b266603f483c92a43e447d4f9c422ae4c41b0c34c04cd9dd8f71463417))
- Commit ID: `95644e1901c13436b5372f5a9301b39856afaacf`
- Short Commit ID: `95644e1`
- Repository Side: `origin` (A.K.A. problem with Spark Unforged)

**Comment by fonnymunkey** [comment]
Sorry I'm late on this, normally I get an email when an issue is posted.

The crash log shows it failed to read the Spark config due to malformed input, this may be caused by either not refreshing the config when switching versions from Spark to Spark Unforged, or changing the format when editing.

Try deleting the config files in the config/spark folder and let them regenerate to default.

**Comment by ProjectHSI** [comment]
It's OK, I haven't played my modpack in a while. I'll quickly try this.

**Comment by ProjectHSI** [comment]
apparently there was an erroneous comma right at end... my modpack takes a while to start up so i'll see if that fixes it, it's about half way loaded.

**Comment by ProjectHSI** [comment]
getting rid of that comma fixed it. thanks!
